name: pixelarticons
description: "Pixel Art Icons made simple for Flutter, powered by pixelarticons"
version: 0.14.0
homepage: https://github.com/libsrcdev/pixelarticons
pixelarticons_commit: c9ecc2da61af
repository: https://github.com/libsrcdev/pixelarticons
issue_tracker: https://github.com/libsrcdev/pixelarticons/issues
documentation: https://github.com/libsrcdev/pixelarticons

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Pixel Art Icons
      fonts:
        - asset: fonts/pixelarticons.otf
