const Set<String> dartKeywords = {
  'abstract',
  'else',
  'import',
  'show',
  'as',
  'enum',
  'in',
  'static',
  'assert',
  'export',
  'interface',
  'super',
  'async',
  'extends',
  'is',
  'switch',
  'await',
  'extension',
  'late',
  'sync',
  'break',
  'external',
  'library',
  'this',
  'case',
  'factory',
  'mixin',
  'throw',
  'catch',
  'false',
  'new',
  'true',
  'class',
  'final',
  'null',
  'try',
  'const',
  'finally',
  'on',
  'typedef',
  'continue',
  'for',
  'operator',
  'var',
  'covariant',
  'Function',
  'part',
  'void',
  'default',
  'get',
  'required',
  'while',
  'deferred',
  'hide',
  'rethrow',
  'with',
  'do',
  'if',
  'return',
  'yield',
  'dynamic',
  'implements',
  'set',
};

const String upstreamOwner = 'halfmage';
const String upstreamRepo = 'pixelarticons';
const String commitsEndpoint =
    'https://api.github.com/repos/$upstreamOwner/$upstreamRepo/commits/master';
const String zipballEndpoint =
    'https://api.github.com/repos/$upstreamOwner/$upstreamRepo/zipball/master';
const String releaseSvgDir = 'release/svg';
const String pubspecCommitKey = 'pixelarticons_commit';
const String pubspecVersionKey = 'version';
