import 'dart:io';

import 'package:icon_font_generator/icon_font_generator.dart';
import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'constants.dart';

String iconIdentifier(String filename) {
  final name = p
      .basenameWithoutExtension(filename)
      .replaceAll(RegExp('[^a-zA-Z0-9]'), '')
      .toLowerCase();
  if (name.isEmpty) throw FormatException('Empty icon name: $filename');
  return RegExp('^[a-z]').hasMatch(name) && !dartKeywords.contains(name)
      ? name
      : 'k$name';
}

/// Generate both artifacts together, using only the current upstream SVGs.
int generateFont({required String projectRoot}) {
  final svgMap = <String, String>{};
  final dir = p.join(projectRoot, releaseSvgDir);
  final files =
      Directory(dir)
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.svg'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final names = <String>{};
  for (final file in files) {
    final name = iconIdentifier(file.path);
    if (!names.add(name)) throw StateError('Duplicate icon name: $name');
    svgMap[name] = file.readAsStringSync();
  }
  if (svgMap.isEmpty) throw StateError('No upstream SVGs found');
  final sortedNames = svgMap.keys.toList()..sort();
  final result = svgToOtf(
    svgMap: {for (final name in sortedNames) name: svgMap[name]!},
    fontName: 'Pixel Art Icons',
    normalize: false,
    ignoreShapes: false,
  );
  final code = StringBuffer(
    "// Generated by pixelarticons_tool. Do not edit.\n"
    "// dart format width=160\n"
    "import 'package:flutter/widgets.dart';\n\n"
    "/// Pixel art icons. Use with Flutter's [Icon] widget.\n"
    "class Pixel {\n  const Pixel._();\n"
    "  static const iconFontFamily = 'Pixel Art Icons';\n"
    "  static const iconFontPackage = 'pixelarticons';\n",
  );
  for (final glyph in result.glyphList) {
    code.writeln(
      '  static const IconData ${glyph.metadata.name} = '
      'IconData(0x${glyph.metadata.charCode!.toRadixString(16)}, '
      'fontFamily: iconFontFamily, fontPackage: iconFontPackage);',
    );
  }
  code.writeln('}');
  Directory(p.join(projectRoot, 'fonts')).createSync(recursive: true);
  Directory(p.join(projectRoot, 'lib')).createSync(recursive: true);
  writeToFile(p.join(projectRoot, 'fonts/pixelarticons.otf'), result.font);
  File(p.join(projectRoot, 'lib/pixel.dart')).writeAsStringSync(
    DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
      pageWidth: 160,
    ).format(code.toString()),
  );
  return result.glyphList.length;
}
