import 'dart:io';
import 'dart:convert';

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'constants.dart';

String iconIdentifier(String filename) {
  final name = p
      .basenameWithoutExtension(filename)
      .replaceAll(RegExp('[^a-zA-Z0-9]'), '')
      .toLowerCase();
  if (name.isEmpty) throw FormatException('Empty icon name: $filename');
  return RegExp('^[a-z]').hasMatch(name) && !dartKeywords.contains(name)
      ? name
      : 'k$name';
}

/// Generate both artifacts together, using only the current upstream SVGs.
int generateFont({required String projectRoot}) {
  final svgMap = <String, String>{};
  final dir = p.join(projectRoot, releaseSvgDir);
  final files =
      Directory(dir)
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.svg'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final names = <String>{};
  for (final file in files) {
    final name = iconIdentifier(file.path);
    if (!names.add(name)) throw StateError('Duplicate icon name: $name');
    svgMap[name] = file.readAsStringSync();
  }
  if (svgMap.isEmpty) throw StateError('No upstream SVGs found');
  final sortedNames = svgMap.keys.toList()..sort();
  final temp = Directory.systemTemp.createTempSync('pixelarticons-font-');
  try {
    final input = Directory(p.join(temp.path, 'svg'))..createSync();
    for (final name in sortedNames) {
      File(p.join(input.path, '$name.svg')).writeAsStringSync(svgMap[name]!);
    }
    final manifest = File(p.join(temp.path, 'codepoints.json'))
      ..writeAsStringSync(
        jsonEncode({
          for (var i = 0; i < sortedNames.length; i++)
            sortedNames[i]: 0xe000 + i,
        }),
      );
    final result = Process.runSync('node', [
      p.join(projectRoot, 'tool', 'generate_font.mjs'),
      input.path,
      temp.path,
      manifest.path,
    ]);
    if (result.exitCode != 0) {
      throw StateError(
        'svgtofont failed. Run npm ci in tool/.\n'
        '${result.stdout}\n${result.stderr}',
      );
    }
    Directory(p.join(projectRoot, 'fonts')).createSync(recursive: true);
    File(p.join(temp.path, 'Pixel Art Icons.ttf'))
        .copySync(p.join(projectRoot, 'fonts/pixelarticons.ttf'));
  } finally {
    temp.deleteSync(recursive: true);
  }
  final code = StringBuffer(
    "// Generated by pixelarticons_tool. Do not edit.\n"
    "// dart format width=160\n"
    "import 'package:flutter/widgets.dart';\n\n"
    "/// Pixel art icons. Use with Flutter's [Icon] widget.\n"
    "class Pixel {\n  const Pixel._();\n"
    "  static const iconFontFamily = 'Pixel Art Icons';\n"
    "  static const iconFontPackage = 'pixelarticons';\n",
  );
  for (var i = 0; i < sortedNames.length; i++) {
    code.writeln(
      '  static const IconData ${sortedNames[i]} = '
      'IconData(0x${(0xe000 + i).toRadixString(16)}, '
      'fontFamily: iconFontFamily, fontPackage: iconFontPackage);',
    );
  }
  code.writeln('  /// All icons indexed by their Dart names.');
  code.writeln('  static const Map<String, IconData> allIcons = {');
  for (final name in sortedNames) {
    code.writeln("    '$name': $name,");
  }
  code.writeln('  };');
  code.writeln('}');
  Directory(p.join(projectRoot, 'fonts')).createSync(recursive: true);
  Directory(p.join(projectRoot, 'lib')).createSync(recursive: true);
  File(p.join(projectRoot, 'lib/pixel.dart')).writeAsStringSync(
    DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
      pageWidth: 160,
    ).format(code.toString()),
  );
  final exampleAssets = Directory(p.join(projectRoot, 'example/assets'));
  exampleAssets.createSync(recursive: true);
  File(p.join(exampleAssets.path, 'icon_vectors.json')).writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert({for (final name in sortedNames) name: svgMap[name]!})}\n',
  );
  return sortedNames.length;
}
